apiVersion: v1
kind: PersistentVolume
metadata:
  name: "tekton-storage"
spec:
  capacity:
    storage: "5Gi"
  accessModes:
    - "ReadWriteMany"
  hostPath:
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "maven-repo-claim"
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "2Gi"

